site_name: Guia de Apoio ao TCC
site_description: Material de apoio para elaboração de Trabalhos de Conclusão de Curso
site_author: IFPR - Campus Paranavaí

theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md

  - ORIENTAÇÕES GERAIS:
      - Visão inicial:
          - Apresentação do guia: orientacoes-gerais/apresentacao.md
          - O que é um TCC: orientacoes-gerais/o-que-e-tcc.md

      - Relação de orientação:
          - Orientador e orientando: orientacoes-gerais/orientador-orientando.md

      - Planejamento do trabalho:
          - Cronograma sugerido: orientacoes-gerais/cronograma.md
          - Organização da rotina de trabalho: orientacoes-gerais/rotina.md

      - Ética e escrita acadêmica:
          - Uso ético de fontes e ferramentas digitais: orientacoes-gerais/etica-fontes-ferramentas.md
          - Escrita acadêmica: orientacoes-gerais/escrita-academica.md
          - Construção de parágrafos: orientacoes-gerais/paragrafos.md
          - Dicas de português: orientacoes-gerais/dicas-portugues.md

      - Finalização:
          - Preparação para a defesa: orientacoes-gerais/defesa.md

  - SEÇÕES DE UM TCC:
      - Visão geral: secoes-tcc/visao-geral.md

      - Elementos iniciais:
          - Título: secoes-tcc/titulo.md
          - Resumo: secoes-tcc/resumo-palavras-chave.md
          - Introdução: secoes-tcc/introducao.md

      - Desenvolvimento:
          - Fundamentação Teórica: secoes-tcc/fundamentacao-teorica.md
          - Metodologia ou Materiais e métodos: secoes-tcc/metodologia.md
          - Tipos de pesquisa: secoes-tcc/tipos-de-pesquisa.md
          - Resultados e discussões: secoes-tcc/resultados-discussoes.md

      - Fechamento:
          - Considerações Finais: secoes-tcc/consideracoes-finais.md
          - Referências bibliográficas: secoes-tcc/referencias.md
          - Anexos e Apêndices: secoes-tcc/apendices-anexos.md
